pipeline{
    agent any
    tools{
        maven "Maven3"
        jdk "OracleJDK8"
    }
    environment{
        cluster='production'
        service='vproappprodsvc'


    }
    stages{
        stage('Deploy to ECS production'){
            steps{
                withAWS( credentials: 'awscreds' , region: 'ap-south-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }

            }
        }
    }
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkinscicd',
               // color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}